dataset:
  path: data/HalfCheetah-v5/expert_data/trajs.npz
  obs_normalize: true 
  num_trajs: 1

total_updates: 50000
batch_size: 32
learning_rate: 3e-4
weight_decay: 0.0

num_workers: 16
pin_memory: true

use_amp: true
grad_clip_norm: 1.0

log_freq: 1000
eval_freq: 5000
n_eval_episodes: 5
final_eval_episodes: 5

save_best: true
checkpoint_freq: 10000

plot_enabled: true
plot_every_eval: true
progress_bar: true

device: auto