seed: 42

algo:
  name: bc
  obs_horizon: 1
  action_horizon: 1
  ema_decay: 0.999
  obs_noise: 0.01
  learning_rate: 3e-4
  weight_decay: 0.0
  grad_clip: 1.0

  actor:
    hidden: 512
    depth: 4
    dropout: 0.0
    action_clip: 1.0

train:
  mode: offline

  dataset:
    path: data/HalfCheetah-v5/expert_data/trajs.npz
    obs_normalize: true
    num_trajs: 1

  sampler:
    type: chunk
    obs_horizon: ${algo.obs_horizon}
    action_horizon: ${algo.action_horizon}

  total_updates: 50000
  batch_size: 32

  log_freq: 1000
  eval_freq: 5000
  n_eval_episodes: 5
  final_eval_episodes: 5

  save_best: true
  checkpoint_freq: 10000
  progress_bar: true
  device: auto

env:
  id: HalfCheetah-v5
  kwargs: {}

  reward:
    model_path: null

logger:
  enabled: false
  type: null

hydra:
  run:
    dir: outputs/${env.id}/${algo.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${env.id}/${algo.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
