seed: 42

algo:
  name: diffusion_bc
  obs_horizon: 1
  action_horizon: 4
  exec_horizon: 1
  ema_decay: 0.999
  obs_noise: 0.01

  scheduler:
    type: ddpm  # ddpm | ddim
    train_steps: 20
    beta_start: 0.0001
    beta_end: 0.02
    num_inference_steps: 20
    eta: 0.0  # ddim-only

  model:
    type: unet  # mlp | unet
    time_emb_dim: 128
    emb_dim: 256
    base_channels: 128
    channel_mults: [1, 2]
    groups: 8

  policy:
    action_clip: 1.0
    use_amp: true

train:
  mode: offline

  dataset:
    type: trajectory
    path: data/HalfCheetah-v5/expert_data/trajs.npz
    obs_normalize: true
    num_trajs: 1

  total_updates: 50000
  batch_size: 32
  learning_rate: 3e-4
  weight_decay: 0.0

  num_workers: 16
  pin_memory: true
  use_amp: true
  use_compile: true
  grad_clip_norm: 1.0

  log_freq: 1000
  eval_freq: 5000
  n_eval_episodes: 5
  final_eval_episodes: 5

  save_best: true
  checkpoint_freq: 10000

  plot_enabled: true
  plot_every_eval: true
  progress_bar: true
  device: auto

env:
  id: HalfCheetah-v5
  num_envs: 64
  eval_num_envs: 64
  kwargs: {}

  normalize:
    enabled: false
    norm_obs: true
    norm_reward: false
    clip_obs: 10.0
    clip_reward: 10.0

  reward:
    model_path: null
    hidden_dim: 256
    scale: 1.0

  compare_reward: null

logger:
  enabled: false
  type: null

hydra:
  run:
    dir: outputs/${env.id}/${algo.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${env.id}/${algo.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
