defaults:
  - env: halfcheetah
  - algo: diffusion
  - train: bc
  - logger: base
  - _self_

seed: 42

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_offline
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
