# Registry key
name: sac

# Policy class name
policy: MlpPolicy

# Passed to sbx.SAC(..., **kwargs)
kwargs:
  # Core SAC hyperparams
  learning_rate: 3e-4
  qf_learning_rate: null
  buffer_size: 1000000
  learning_starts: 10000
  batch_size: 1024
  tau: 0.005
  gamma: 0.99

  # Update schedule
  train_freq: 1
  gradient_steps: 8
  policy_delay: 1

  # Entropy
  ent_coef: auto
  target_entropy: auto

  # Logging / misc
  tensorboard_log: null
  verbose: 1
  seed: ${seed}
  device: auto

  # Policy kwargs
  policy_kwargs: {}
